bot:
  token: fill_me_in
  username: Todd
  fullUsername: ForemanToddBot
  check:
    initialDelay: 60000
    fixedDelay: 60000

notifications:
  max: 10

foreman:
  baseUrl: https://dashboard.foreman.mn
